from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView
urlpatterns = [
    path('',views.index,name='index'),
    path('tutor_register/',views.tutor_register,name='tutor_register'),
    path('add_student/',views.add_student,name='add_student'),
    path('update_profile/', views.update_profile, name='update_profile'),
    path('login/',views.login,name='login'),
    path('studentindex/',views.studentindex,name='studentindex'),
    path('tutorindex/',views.tutorindex,name='tutorindex'),
    path('adminindex/',views.adminindex,name='adminindex'),
    path('student_list/',views.student_list,name='student_list'),
    path('view_profile/',views.view_profile,name='view_profile'),
    path('view_student_list/',views.view_student_list,name='view_student_list'),
    path('view_student_profile/',views.view_student_profile,name='view_student_profile'),
    path('tutor_lists/',views.tutor_lists,name='tutor_lists'),
    path('manage_tutor/',views.manage_tutor,name='manage_tutor'),
    path('approved_tutors',views.approved_tutors,name='approved_tutors'),
    path('rejected_tutors/',views.rejected_tutors,name='rejected_tutors'),
    path('approve_tutor/',views.approve_tutor,name='approve_tutor'),
    path('reject_tutor/',views.reject_tutor,name='reject_tutor'),
    path('create_job_list/',views.create_job_list,name='create_job_list'),
    path('manage_job_list/',views.manage_job_list,name='manage_job_list'),
    path('edit_job_list/',views.edit_job_list,name='edit_job_list'),
    path('delete_job_list/',views.delete_job_list,name='delete_job_list'),
    path('available_jobs/',views.available_jobs,name='available_jobs'),
    path('student_job_list/',views.student_job_list,name='student_job_list'),
    path('student_profile/',views.student_profile,name='student_profile'),
    path('verify_supplies',views.verify_supplies,name='verify_supplies'),
    path('apply_for_job', views.apply_for_job, name='apply_for_job'),
    path('view_student_applications/',views.view_student_applications,name='view_student_applications'),
    path('track_applications/',views.track_applications,name='track_applications'),
    path('tutor_profile/',views.tutor_profile,name='tutor_profile'),
    path('tutor_edit_profile/',views.tutor_edit_profile,name='tutor_edit_profile'),
    path('add_training_session',views.add_training_session,name='add_training_session'),
    path('training_session_list/', views.training_session_list, name='training_session_list'),
    path('student_training_session/',views.student_training_session,name='student_training_session'),
    path('enroll_training_session/',views.enroll_training_session,name='enroll_training_session'),
    path('export_training_session_attendees/',views.export_training_session_attendees,name='export_training_session_attendees'),
    path('application_list/',views.application_list,name='application_list'),
    path('export_job_applications/',views.export_job_applications,name='export_job_applications'),
    path('export_students_to_excel/',views.export_students_to_excel,name='export_students_to_excel'),
    path('delete_training_session',views.delete_training_session,name='delete_training_session')
]