# Generated by Django 5.1.3 on 2024-11-21 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='is_approved',
        ),
    ]
