# Generated by Django 5.1.3 on 2024-11-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0002_remove_tutor_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
