# Generated by Django 5.1.3 on 2024-11-21 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0003_tutor_is_approved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
