# Generated by Django 5.1.3 on 2024-11-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0005_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
