# Generated by Django 5.1.3 on 2024-11-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0006_tutor_experience_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='pswd',
            field=models.CharField(default='', max_length=20),
        ),
    ]
