# Generated by Django 5.1.3 on 2024-11-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0009_joblisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='course',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
