# Generated by Django 5.1.3 on 2024-11-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0012_alter_student_course_alter_student_student_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='supply',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
