# Generated by Django 5.1.3 on 2024-11-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0013_student_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='student_pictures/'),
        ),
    ]
