# Generated by Django 5.1.3 on 2024-11-29 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0015_student_verified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
