# Generated by Django 5.1.3 on 2024-12-02 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0017_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('instructor', models.CharField(max_length=255)),
                ('attendees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegeapp.student')),
            ],
        ),
    ]
