# Generated by Django 5.1.3 on 2024-12-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0019_rename_name_trainingsession_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='attendees',
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='collegeapp.student'),
        ),
    ]
