# Generated by Django 5.1.3 on 2024-12-17 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0020_remove_trainingsession_attendees_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
